### ISSUE TITLE
Most options don't work on a mi4 firmware

### ISSUE THREAD

**Issue by KlausMu** [scooterteam/bw-patcher#4]
Hi, thanks a lot for your work!

I'm using the script on a mi4 with firmware version 2.5.3_0011.0013

**rsls**
`RSLS can't be applied`

**dms**
works

**sld**
`SLD can't be applied`

**rfm**
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "\bw-patcher\bwpatcher\__main__.py", line 37, in <module>
    output_data = patch_firmware(args.model, data, args.patches.split(","))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\bw-patcher\bwpatcher\utils.py", line 60, in patch_firmware
    res = patch_map[patch](patcher)()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\bw-patcher\bw-patcher\bwpatcher\core.py", line 44, in region_free
    raise NotImplementedError()
NotImplementedError
```

**fdv**
works

**mss**
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "\bw-patcher\bwpatcher\__main__.py", line 37, in <module>
    output_data = patch_firmware(args.model, data, args.patches.split(","))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\bw-patcher\bwpatcher\utils.py", line 58, in patch_firmware
    res = patch_map[patch](patcher)(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\bw-patcher\bwpatcher\core.py", line 63, in motor_start_speed
    raise NotImplementedError()
NotImplementedError```

**Comment by encryptize** [comment]
Not every patch is available for every scooter. You can see the list of patches available for your scooter in the webui or by analyzing the `app.py` file. Currently, these include RSLS, DMS, SLD and FDV for Mi4. The others will return NotImplementedError.

>firmware version 2.5.3_0011.0013

Patches for Mi4 have only been prepared for MCU version 0011. They have not yet been updated for newer firmware versions.

**Comment by encryptize** [comment]
@aniscatalin20 I'll be doing a rewrite of patches for the 4 series this week, and I'll make sure there's more universal support for all firmware versions. I can't share the 0011 firmware due to copyright reasons.

**Comment by encryptize** [comment]
@KlausMu have you tried with CLI?. The web version has a bit of a delay with updates.

**Comment by encryptize** [comment]
mi-fw-info, 133120bytes.

**Comment by encryptize** [comment]
Sorry, I have misunderstood you at the beginning. I do not own a Mi4 to do the 0013 dump directly from the controller, and thus I am not able to verify why the patching is not working on your file.

**Comment by Ilkan0342567** [comment]
Hello, i have the same scooter and when i flash my scooter with the file in https://mi-fw-info.streamlit.app/#mi-firmware-info i get the error 43 in my scooter with the patch and without patch, so i can't accelerate and use it, did you get somme solution for this problem ?
